replicaCount: 1

image:
  repository: chinmayiaradhya/java-producer
  tag: dev-local
  pullPolicy: IfNotPresent

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka-broker-0.kafka-broker-headless.infra.svc.cluster.local:9092
  - name: KAFKA_TOPIC
    value: raw_messages

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80