kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 18080          # ← AKHQ on localhost:18080 instead
    protocol: TCP
  - containerPort: 5432
    hostPort: 15432          # ← Postgres on localhost:15432
    protocol: TCP